services:

  db:
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=workshop
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=mydb
    ports:
      - '5432:5432'
    networks:
      - pg_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - pg_network
    depends_on:
      - db 

networks:
  pg_network:

volumes:
  postgres_data: